apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-golang-dev
spec:
  selector:
    matchLabels:
      app: server-golang-dev
  replicas: 2
  template:
    metadata:
      labels:
        app: server-golang-dev
    spec:
      containers:
      - name: server-golang-dev
        image: arthurandraadee/server-golang:1.0.7
        resources:
          requests:
            cpu: 8m
            memory: 20Mi
          limits:
            cpu: 12m
            memory: 25Mi
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: server-golang-dev
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
