apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-golang-dev
spec:
  selector:
    matchLabels:
      app: server-golang-dev
  replicas: 2
  template:
    metadata:
      labels:
        app: server-golang-dev
    spec:
      containers:
      - name: server-golang-dev
        image: arthurandraadee/server-golang:1.0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: ENVIRONMENT_TYPE
            value: DEV
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
