apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-golang-hml
spec:
  selector:
    matchLabels:
      app: server-golang-hml
  replicas: 3
  template:
    metadata:
      labels:
        app: server-golang-hml
    spec:
      containers:
      - name: server-golang-hml
        image: arthurandraadee/server-golang:1.0.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: ENVIRONMENT_TYPE
            value: HML
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
