apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: server-golang-hml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-golang-hml
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
