apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-golang-prd
spec:
  selector:
    matchLabels:
      app: server-golang-prd
  replicas: 4
  template:
    metadata:
      labels:
        app: server-golang-prd
    spec:
      containers:
      - name: server-golang-prd
        image: arthurandraadee/server-golang:1.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: ENVIRONMENT_TYPE
            value: PRD
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
