apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-golang-prd
spec:
  selector:
    matchLabels:
      app: server-golang-prd
  replicas: 4
  template:
    metadata:
      labels:
        app: server-golang-prd
    spec:
      containers:
      - name: server-golang-prd
        image: arthurandraadee/server-golang:1.0.7
        resources:
          requests:
            cpu: 20m
            memory: 40Mi
          limits:
            cpu: 30m
            memory: 50Mi
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: server-golang-prd
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
